(function(g){var window=this;var v4=function(a){var b={format:a.o,languageCode:a.l,languageName:a.C,displayName:g.jI(a),kind:a.A,name:a.B,id:a.ka,is_servable:a.M,is_default:a.isDefault,is_translateable:a.F,vss_id:a.D};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},w4=function(a){return a.g?a.g.languageCode:a.l},Vya=function(a,b){var c=new g.iI;
c.l=a.l;c.C=a.C;c.B=a.B;c.A=a.A;c.isDefault=!1;c.F=a.F;c.D=a.D;c.H=a.H;c.g=b;return c},Wya=function(a){a=g.pd(window.document,"track",void 0,a.g);
for(var b=0;b<a.length;b++)g.Id(a[b])},Xya=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},x4=function(a){if(!Yya.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Zya,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},y4=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.mQ.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.C=f;this.l=k},z4=function(a,b,c,d,e){g.mQ.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.l=[]},B4=function(a){a=void 0===a?{}:a;
var b="_"+A4++;return new z4(0,0x8000000000000,0,b,a)},C4=function(a,b,c,d,e,f){var k={};
g.Ga(k,b);g.Ga(k,a.params);g.Ga(k,c);var l={};g.Ga(l,b.ib);a.params.ib&&g.Ga(l,a.params.ib);g.Ga(l,c.ib);k.ib=l;g.W.call(this,{G:"div",L:"caption-window",U:{id:"caption-window-"+a.id,dir:1==k.lk?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},J:[{G:"span",L:"captions-text"}]});this.o=[];this.I=!1;this.D=a;this.C=[];this.F=[];this.ra=e;this.oa=f;this.B=null;this.P=.96*e;this.da=.96*f;this.l=k;this.ma=c;this.A=this.sa["captions-text"];this.fa=null!=this.A.style["box-decoration-break"]||
null!=this.A.style["-webkit-box-decoration-break"];this.K=d/360*16;this.type=0;this.Y=this.K*$ya(l);a=new g.IF(this.element,!0);g.M(this,a);a.subscribe("dragstart",this.CN,this);a.subscribe("dragmove",this.BN,this);a.subscribe("dragend",this.AN,this);this.ba=this.ca=0;a="";this.l.xk&&(a=x4(this.l.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.xk+")");b={"background-color":a,display:!1===this.l.isVisible?"none":"","text-align":aza[this.l.textAlign]};this.fa&&(b["border-radius"]=a?this.Y/
8+"px":"");g.qh(this.element,b);switch(this.l.Ug){case 0:case 1:case 2:g.S(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.S(this.element,"ytp-caption-window-bottom")}},$ya=function(a){var b=1+.25*(a.oj||0);
if(0==a.offset||2==a.offset)b*=.8;return b},D4=function(a,b){var c={},d=b.background?b.background:a.l.ib.background;
if(null!=b.Ye||b.background){var e=null!=b.Ye?b.Ye:a.l.ib.Ye;d=x4(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.fa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Y/8+"px")}if(null!=b.oj||null!=b.offset)c["font-size"]=a.K*$ya(b)+"px";d=1;e=b.color||a.l.ib.color;if(b.color||null!=b.Hh)e=x4(e),d=null==b.Hh?a.l.ib.Hh:b.Hh,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.Xh;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Pw&&
(k=e=b.Pw);var l=a.K/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';
break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.xE()?'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e=
'"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.ib.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.ts&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");b.Br&&(c.visibility="hidden");return c},bza=function(a,b,c){a.I=a.I||!!c;
var d={};g.Ga(d,a.l.ib);g.Ga(d,c||b.l);g.Ga(d,a.ma.ib);c=a.C[0];if(c&&d.background==c.background&&d.Ye==c.Ye&&!!d.Br==!!c.Br&&d.Xh==c.Xh){var e;for(e=0;e<a.C.length;e++)if(Xya(d,a.C[e])){var f=a.F[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.Cd("SPAN");g.qh(f,D4(a,e));a.F[0].appendChild(f);e=1}a.F.length=e;a.C.length=e}else a.F.length=0,a.C.length=0,f=g.Cd("SPAN"),g.qh(f,D4(a,d)),a.A.appendChild(f);a.B&&a.B.parentNode!=f&&(g.Id(a.B),f.appendChild(a.B));c=(k=g.v(b.text))?b.text.split("\n"):
[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.o.length||!b.C){if(0<e||0!=a.o.length){var m=g.Cd("BR");f.appendChild(m)}f.appendChild(g.Dd("\u00a0"));a.B=g.Dd("\u00a0");f.appendChild(a.B)}l&&(m=a.B,m.parentNode&&m.parentNode.insertBefore(k?g.Dd(l):l,m))}a.C.push(d);a.F.push(f);a.o.push(b)},cza=function(){},F4=function(){this.A=this.l=this.mode=this.o=0;
this.B=new E4(this);this.C=new E4(this);this.g=[];this.clear()},eza=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Rm:a,
Sm:b,result:0};a=dza[a];b=dza[b];if(a&128){if(!(b&128)&&0!=c.g&&c.l==b)return{Rm:a,Sm:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Rm:a,Sm:b,result:2};return{Rm:a,Sm:b,result:3}},gza=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.g.clear(),a.C.g.clear()):(a.A=0,fza(a.B,b,c,d))},hza=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.l=d.time;0==d.type?gza(a,d.Kw,d.Lw,b):1==d.type&&a.o&496&&fza(a.C,d.Kw,d.Lw,b)}a.g.length=0},G4=function(){this.g=0},H4=function(){this.l=this.o=this.g=0},I4=function(){this.timestamp=this.ye=0},J4=function(a){this.o=[];
for(var b=0;15>=b;b++){this.o[b]=[];for(var c=0;32>=c;c++)this.o[b][c]=new I4}this.g=this.l=this.Kc=0;this.style=new G4;this.B=a;this.A=0},K4=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.B.l+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.o[m][q];
if(0!=r.ye){0==c&&(c=m,d=q);n=String.fromCharCode(r.ye);var u=r.timestamp;u<e&&(e=u);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.ye||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.A(c,d,e,l,f)}else for(d=c=0,f=e=a.B.l+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.o[k][m],r=q.ye,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),u=q.timestamp,u<=e&&(e=u),l+=n,q.reset()),32==m||0==r)l&&b.A(c,d,e,f,l),e=f,l="",d=c=0},mza=function(a,b){switch(a){case 0:return iza[(b&127)-32];
case 1:return jza[b&15];case 2:return kza[b&31];case 3:return lza[b&31]}return 0},L4=function(a){return a.o[a.Kc][a.l]},M4=function(a,b,c){2<=b&&1<a.l&&(--a.l,L4(a).ye=0);
var d=L4(a);d.timestamp=a.B.l+0;d.ye=mza(b,c);32>a.l&&a.l++},nza=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.o[b+e][f].ln(a.o[c+e][f])},N4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.o[b+d][e].reset()},O4=function(a){a.Kc=0<a.g?a.g:1;
a.l=1;N4(a,0,15)},P4=function(a){this.A=a;
this.B=0;this.style=new G4;this.C=new J4(a);this.D=new J4(a);this.F=new J4(a);this.l=this.C;this.o=this.D;this.g=this.l},Q4=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:K4(d,c),O4(a.l),O4(a.o),d.Kc=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.A.mode=1<<d.A;e?d.l=1:d.g!=b&&(d.g>b?(K4(d,c),N4(d,d.Kc-d.g,b)):d.Kc<b&&(b=d.g),d.g=b)},oza=function(a){a.style.set(1);
a.g=a.o;a.g.g=0;a.g.style=a.style;a.A.mode=1<<a.g.A},pza=function(a){a.style.set(4);
a.g=a.F;a.g.style=a.style;a.A.mode=1<<a.g.A},E4=function(a){this.l=a;
this.g=new H4;this.B=0;this.o=new P4(a);this.C=new P4(a);this.A=this.o},fza=function(a,b,c,d){a.g.update();
b=eza(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Rm;c=b.Sm;if(32<=e||!e)a.l.mode&a.l.o&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.g,b&96&&M4(a,0,b),c&96&&M4(a,0,c),0!=b&&0!=c&&3==a.style.g&&K4(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.o=e,b.l=c,b.g=2,b=e&8?a.C:a.o,a.A=b,a.l.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.g?1:0),(a.l.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.g?1:0))&a.l.o))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.Kc;break;case 3:if(d!=c.Kc){if(d<c.g&&(d=c.g,d==c.Kc))break;var f=1+c.Kc-c.g,k=1+d-c.g;nza(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));N4(c,b,e)}}c.Kc=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:M4(b.g,0,32);break a;case 48:57==c?(b=b.g,L4(b).ye=0,32>b.l&&b.l++):M4(b.g,1,c&15)}break;case 2:c&32&&M4(b.g,2,c&31);break;case 3:c&32&&M4(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:oza(b);break;case 33:b=
b.g;1<b.l&&(--b.l,L4(b).ye=0);break;case 36:b=b.g;d=L4(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.o[a][c]==d){for(;32>=c;c++)b.o[a][c].reset();break}break;case 37:Q4(b,2,d);break;case 38:Q4(b,3,d);break;case 39:Q4(b,4,d);break;case 40:M4(b.g,0,32);break;case 41:b.style.set(2);b.g=b.l;b.g.g=0;b.g.style=b.style;b.A.mode=1<<b.g.A;break;case 42:d=b.F;d.g=15;d.style.set(4);O4(d);pza(b);break;case 43:pza(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:K4(a,d)}N4(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.Kc){++a.Kc;a.l=1;break b}case 3:}2>a.g&&(a.g=2,a.Kc<a.g&&(a.Kc=a.g));b=a.Kc-a.g+1;K4(a,d);nza(a,b,b+1,a.g-1);N4(a,a.Kc,1)}break;case 46:N4(b.o,0,15);break;case 47:K4(b.l,d);d=b.o;a=b.A.l+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.o[c][e].timestamp=a;d=b.o;b.o=b.l;b.l=d;oza(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.l+=c&3)&&(b.l=32)}}},R4=function(){},S4=function(a){this.l=a;
this.g=null},rza=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.Ur("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");qza(d,e,k,b,f,a.firstChild,{},c)},qza=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.ts=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");T4.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new y4(a,b,c,d,n.nodeValue,e||0<m,g.Yb(k)?void 0:k));else{var q={};g.Ga(q,k);qza(a,b,c,d,e||0<m,n,q,l)}}},U4=function(){this.l={};
this.g=null},V4=function(a){this.A={};
this.I={};this.K={};this.B="_"+A4++;this.C=a;this.H={};this.g=null;this.D=[];this.l=null;this.F=!0},W4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},X4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},Y4=function(a,b){var c=W4(a,b);
if(void 0!=c)return c},Z4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return T4.test(c),c},sza=function(a,b){var c={},d=b.getAttribute("ws");
g.Ga(c,d?a.K[d]:a.C);d=Y4(b,"mh");null!=d&&(c.Hs=d);d=Y4(b,"ju");null!=d&&(c.textAlign=d);d=Y4(b,"pd");null!=d&&(c.lk=d);d=Z4(b,"wfc");null!=d&&(c.windowColor=d);d=W4(b,"wfo");void 0!=d&&(c.xk=d/255);return c},tza=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ga(c,a.I[d]);d=Y4(b,"ap");null!=d&&(c.Ug=d);d=W4(b,"cc");null!=d&&(c.YH=d);d=W4(b,"ah");null!=d&&(c.xi=d);d=W4(b,"rc");null!=d&&(c.hp=d);d=W4(b,"av");null!=d&&(c.Ri=d);return c},uza=function(a,b,c,d){var e={};
g.Ga(e,tza(a,b));g.Ga(e,sza(a,b));d?Xya(e,a.C)?(d=a.B,e=a.C):d="_"+A4++:d=b.getAttribute("id")||"0";a=W4(b,"t")+c;b=W4(b,"d")||0x8000000000000;return new z4(a,b,0,d,e)},wza=function(a,b,c){var d=[],e=b.getAttribute("w")||a.B,f=!!X4(b,"a");
c=(W4(b,"t")||0)+c;var k=W4(b,"d")||5E3;f||(!a.F&&a.l&&a.l.windowId==e&&a.l.end>c&&(a.l.end=c),a.l&&"\n"==a.l.text&&(a.l.text=""));var l=f?6:5,m=a.A[b.getAttribute("p")],n=b.childNodes;n.length&&(a.F=null!=b.getAttribute("d"));b={};for(var q=0;q<n.length;b={Gh:b.Gh},q++){var r=n[q];b.Gh=void 0;0<q&&(f=!0);var u=void 0;1==r.nodeType&&(u=r);b.Gh=u&&"s"==u.tagName?vza(a,u,c,k,e,f,l):new y4(c,k,l,e,r.textContent||"",f,m);if(!f&&(r=a.D.find(function(a){return function(b){return b.text===a.Gh.text&&b.windowId===
a.Gh.windowId}}(b)))){r.end=b.Gh.end;
a.l=r;continue}d.push(b.Gh);a.l=b.Gh}return d},vza=function(a,b,c,d,e,f,k){var l=b.textContent?b.textContent:"";
a=a.A[b.getAttribute("p")];b=W4(b,"t")||0;return new y4(c+b,d-b,k,e,l,f,a)},$4=function(a,b,c){this.D=c;
this.version=this.B=this.C=this.g=0;this.l=new window.DataView(a);this.o=[]},a5=function(a){var b=a.g;
a.g+=1;return a.l.getUint8(b)},xza=function(a){var b=a.g;
a.g+=4;return a.l.getUint32(b)},b5=function(a,b){this.l=a;
this.track="CC3"==b.C?4:0;this.g=new F4;this.g.o=1<<this.track},zza=function(a){if(g.v(a))return!1;
a=new $4(a,8,0);return yza(a)},yza=function(a){if(!(a.g<a.l.byteLength)||1380139777!=xza(a))return!1;
a.version=a5(a);if(1<a.version)return!1;a5(a);a5(a);a5(a);return!0},Aza=function(){this.l=[];
this.g=[]},c5=function(a,b){return b?a.g.concat(a.l):a.g},d5=function(a,b){switch(b.A){case "asr":var c=a.l;
g.Ma(c,(0,g.z)(b.I,b))||c.push(b);break;default:c=a.g,g.Ma(c,(0,g.z)(b.I,b))||c.push(b)}},e5=function(){this.g=null},Bza=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.ts=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new y4(b,c,d,e.id,q.nodeValue,f||0<n,g.Yb(l)?void 0:l),m.push(q),e!=a.g&&e.l.push(q);else{var r={};g.Ga(r,l);Bza(a,b,c,d,e,!0,q,r,m)}}},f5=function(a){var b=0;
a=g.ma(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+(0,window.parseFloat)(c.value);return 1E3*b},g5=function(a){g.L.call(this);
this.bz=!!a;this.l=new Aza;this.D=[];this.g=null},Dza=function(a){var b={};
if(a=w4(a))b.lang=a,Cza.test(a)&&(b.lk=1);return b},Eza=function(a,b,c,d,e){d=d||0;
e=e||0;if(!g.v(b)){var f=new window.DataView(b);1718909296==f.getUint32(4)&&(f=g.EI(f,1835295092),b=b.slice(f.dataOffset,f.dataOffset+f.size),zza(b)||(b=g.de(new window.Uint8Array(b))))}if(g.v(b)){if("WEBVTT"==b.substring(0,6))return a.g||(a.g=new e5),a.g.o(b,d);b=g.Ur(b);if(!b||!b.firstChild)return[];a.g||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.g=new V4(Dza(c)):a.g=new U4:a.g=new S4(Dza(c)));return a.g.o(b,d)}try{if(zza(b))return a.g||(a.g=
new b5(e,c)),a.g.o(b,d)}catch(k){g.MD(k)}return[]},h5=function(a){g5.call(this,a.Ym);
this.A=void 0;this.o=null;this.D=a.captionTranslationLanguages},i5=function(){this.ob=[]},j5=function(a,b,c,d,e,f){g.L.call(this);
this.K=a;this.A=b;this.C=new i5;this.g=null;this.H=d;this.M=f;this.l=this.o=null;this.F=c;this.D=e||!1;this.I=new g.Xt(this.vz,1E3,this);g.M(this,this.I);this.B=new g.DF(this);g.M(this,this.B);this.B.O(b,"seekto",this.AA);this.AA(b.getCurrentTime());this.vz()},Fza=function(a,b){var c=a.g;
a.g=g.Ja(a.F.hh(b).Ga);c!=a.g&&a.M&&a.M()},Gza=function(a,b){var c=g.kK(b,a.K,{}).Qa(),d={format:"RAW",
withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.l=g.LE(c,d,3,100).then((0,g.z)(a.jS,a));a.o=b;c=a.C;d=a.o.Ga[0].xa;var e=g.fb(c.ob,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.ob[e-1]&&e<c.ob.length&&1==c.ob[e]-d?(g.Ta(c.ob,e),g.Ta(c.ob,e-1)):0<e&&1==d-c.ob[e-1]?c.ob[e-1]=d:e<c.ob.length&&1==c.ob[e]-d?c.ob[e]=d:(g.ab(c.ob,e,0,d),g.ab(c.ob,e+1,0,d)))},k5=function(a,b){g5.call(this);
this.o=a;this.A=b;this.B=null;this.C=!1},Hza=function(a,b){if(b in a.o.g)return a.o.g[b];
if(g.JK(a.o))for(var c in a.o.g){var d=a.o.g[c];if(g.gH(d.info.mimeType)&&("386"!=c||!g.Y(a.A).experiments.g("html5_manifestless_captions_fmt3_killswitch")))return d}return null},Iza=function(a,b){return a.za||g.Y(b).Ma&&null!=a.pa&&null!=a.pa.g.rawcc},l5=function(a,b,c,d,e,f){C4.call(this,a,b,c,d,e,f);
this.type=1},m5=function(a,b,c,d,e,f){C4.call(this,a,b,c,d,e,f);
g.S(this.element,"ytp-caption-window-rollup");this.type=2;this.H=this.M=0;this.N=window.NaN;this.ia=null;this.X=new g.Xt(this.nS,433,this);g.M(this,this.X)},n5=function(a){if(!a.M){var b=g.Cd("SPAN");
g.qh(b,D4(a,a.l.ib));a.A.appendChild(b);b.appendChild(g.Dd("M"));var c=b.offsetHeight,d=g.Cd("BR");b.appendChild(d);b.appendChild(g.Dd("M"));a.M=b.offsetHeight-c;a.A.removeChild(b)}return a.M},o5=function(a,b,c,d){g5.call(this,d);
c=c||g.YD(a).hl||"";c=c.split("_").join("-");this.B=g.dE(a,{hl:c});this.A=b;this.C={};this.o=null},r5=function(a){g.sV.call(this,a);
g.RG({YTP_CLICK_FOR_SETTINGS:"Click $GEAR_ICON for settings",YTP_SAMPLE_SUBTITLES:"Captions look like this"});this.A=g.Y(a);this.l=a.ea();this.oa=g.WU(a);this.K=a;var b=null,c=g.iD("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.SC(c));this.ba=b;this.C={ib:{}};this.H={ib:{}};this.M=[];this.P={};this.Y={};this.N=!1;this.ra="1"==this.l.qc.cc_auto_caps||"1"==this.A.Zb.cc_auto_caps;b="3"==this.A.o&&!!a.app.B&&!!a.app.B.g.textTracks;this.F=(c=this.A.experiments.g("web_player_native_controls_live_captions_fix"))?
b&&!this.l.za:b;this.ia=c&&b&&this.l.za;c=b=this.o=this.B=this.D=this.I=this.X=this.ma=null;this.F||(b=new g.Ut(this.ZD,void 0,this),g.M(this,b),c=new g.Xt(this.aU,2E3,this),g.M(this,c));this.da=b;this.fa=c;this.W=new g.DF(this);g.M(this,this.W);this.F||this.W.O(a,"resize",this.Nu);this.W.O(a,"onPlaybackAudioChange",this.lP);this.W.O(a,"crn_captions",this.KL,this);this.W.O(a,"crx_captions",this.LL,this);p5(this,q5(this,"display-settings")||{})},Jza=function(a){if(a.l.captionTracks.length)var b=a.g.getAudioTrack().Hw;
if("FORCED_ON"==b||1==a.A.Yg||1==a.l.Yg||"alwayson"==g.jO(a.l,"yt:cc"))return!0;if(2==a.A.Yg){var c=q5(a,"module-enabled");if(null!=c)return!!c}return"ON"==b||"on"==g.jO(a.l,"yt:cc")},Kza=function(a,b){if(a.B){var c=c5(a.B.l,b||a.ra);
if(a.D&&a.D.g)return a.D.g;for(var d=[a.l.Xg,a.A.Xg,g.jO(a.l,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(w4(c[f])==d[e])return c[f];return a.D&&a.D.Lq?a.D.Lq:(d=c.find(function(a){return a.isDefault}))?d:c[0]||a.D&&a.D.Pk}return null},Lza=function(a,b){for(var c=a.K.app.B.g.textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},s5=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.N=c);a.o=b;a.load(d)},Mza=function(a,b){var c=g.F_(a.oa,!0).height;
if(!c)return null;var d=a.oa.Pa();switch(null!=b.params.Hs?b.params.Hs:b.params.LU?2:1<b.l.length?1:0){case 1:return new l5(b,a.C,a.H,c,d.width,d.height);case 2:return new m5(b,a.C,a.H,c,d.width,d.height);default:return new C4(b,a.C,a.H,c,d.width,d.height)}},p5=function(a,b,c){var d=t5.ib;
a.C={};g.Ga(a.C,t5);a.C.ib={};g.Ga(a.C.ib,d);a.H={ib:{}};var e=b.backgroundOverride?a.H:a.C,f=b.background||d.background;T4.test(f);e.ib.background=f;e=b.colorOverride?a.H:a.C;f=b.color||d.color;T4.test(f);e.ib.color=f;e=b.windowColorOverride?a.H:a.C;f=b.windowColor||t5.windowColor;T4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.H:a.C;f=b.backgroundOpacity;null==f&&(f=d.Ye);e.ib.Ye=f;e=b.fontSizeIncrementOverride?a.H:a.C;f=b.fontSizeIncrement;null==f&&(f=d.oj);e.ib.oj=f;e=b.textOpacityOverride?
a.H:a.C;f=b.textOpacity;null==f&&(f=d.Hh);e.ib.Hh=f;e=b.windowOpacityOverride?a.H:a.C;f=b.windowOpacity;null==f&&(f=t5.xk);e.xk=f;e=b.charEdgeStyleOverride?a.H:a.C;f=b.charEdgeStyle;null==f&&(f=d.Xh);e.ib.Xh=f;e=b.fontFamilyOverride?a.H:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.ib.fontFamily=f;a.loaded&&a.Nu();c&&u5(a,"display-settings",b)},Oza=function(a,b){if(b&&!a.I){var c=B4({lk:0,
lang:"en"});a.I=[c,new y4(c.start,c.end-c.start,0,c.id,g.V("YTP_SAMPLE_SUBTITLES"))];g.hV(a.g,a.I)}else!b&&a.I&&(Nza(a,a.I),a.I=null)},Nza=function(a,b){g.jV(a.g,b);
(0,g.B)(b,function(a){g.Ua(this.M,a)},a);
a.da.Yk()},Pza=function(a,b){return a&&g.v(a)&&T4.test(a)?a:b},Qza=function(a,b){return g.ua(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},Sza=function(a,b){if(a&&g.v(a)){var c=Rza.indexOf(a);
return-1!=c?c:b}return b},Uza=function(a,b){if(a&&g.v(a)){var c=Tza.indexOf(a);
return-1!=c?c:b}return b},Vza=function(a,b){return g.ua(a)&&!(0,window.isNaN)(a)?g.ad(a,-2,4):b},q5=function(a,b){if(!a.ba)return null;
try{var c=a.ba.get(b)}catch(d){a.ba.remove(b)}return c},u5=function(a,b,c){if(a.ba)try{a.ba.set(b,c)}catch(d){}};
g.oI.prototype.Mn=g.da(2,function(a){return(a=this.fi(a))?a.l:0});
g.zK.prototype.Mn=g.da(1,function(){return 0});
g.iI.prototype.I=g.da(0,function(a){return a?this.toString()==a.toString():!1});
var Cza=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,Zya=/#(.)(.)(.)/,Yya=/^#(?:[0-9a-f]{3}){1,2}$/i,T4=/^#(?:[0-9a-f]{3}){1,2}$/i,Tza="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" "),Rza=["none","raised","depressed","uniform","dropShadow"];var aza=["left","right","center"];var t5={windowColor:"#080808",xk:0,textAlign:2,Ug:7,xi:50,Ri:100,ib:{background:"#080808",Ye:.75,Xh:0,color:"#fff",fontFamily:4,oj:0,Hh:1,offset:1}};g.p(y4,g.mQ);g.p(z4,g.mQ);var A4=0;g.p(C4,g.W);g.h=C4.prototype;g.h.CN=function(a,b){var c=g.Gh(this.element,this.element.parentElement);this.ca=a-c.x;this.ba=b-c.y;g.S(this.element,"ytp-dragging")};
g.h.BN=function(a,b){var c=g.Jh(this.element),d=a-this.ca-.02*this.ra,e=b-this.ba-.02*this.oa,f=(d+c.width/2)/this.P*3;f=Math.floor(g.ad(f,0,2));var k=(e+c.height/2)/this.da*3;k=Math.floor(g.ad(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.P;d=100*g.ad(d,0,1);c=(e+k/2*c.height)/this.da;c=100*g.ad(c,0,1);this.D.params.Ug=l;this.D.params.Ri=c;this.D.params.xi=d;this.l.Ug=l;this.l.Ri=c;this.l.xi=d;this.QC()};
g.h.AN=function(){g.sq(this.element,"ytp-dragging")};
g.h.QC=function(){this.Ni(this.o)};
g.h.Xb=function(){return this.type};
g.h.Ni=function(a){var b=Math.min(this.Yx(),this.P),c=this.Xx();g.qh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.kq(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var d=.96*this.l.xi+2,e=this.l.Ug;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.A.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=
b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-d+"%"}b=.96*this.l.Ri+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.qh(this.element,a)};
g.h.kq=function(a){var b;for(b=0;b<a.length&&a[b]==this.o[b];b++);if(this.I||this.o.length>b)b=0,this.I=!1,this.o=[],this.C=[],this.F=[],this.B=null,g.Gd(this.A);for(;b<a.length;b++)bza(this,a[b])};
g.h.Yx=function(){return 0};
g.h.Xx=function(){return 0};cza.prototype.A=function(){};F4.prototype.clear=function(){this.A=this.l=this.mode=0;this.g=[];this.reset()};
F4.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var dza=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];G4.prototype.set=function(a){this.g=a};
G4.prototype.get=function(){return this.g};
H4.prototype.clear=function(){this.g=0};
H4.prototype.update=function(){this.g=2==this.g?1:0};
H4.prototype.matches=function(a,b){return 0!=this.g&&a==this.o&&b==this.l};
I4.prototype.ln=function(a){this.ye=a.ye;this.timestamp=a.timestamp};
I4.prototype.reset=function(){this.timestamp=this.ye=0};
J4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.o[b][c];a=0==d.ye?a+"_":a+String.fromCharCode(d.ye)}a+="\n"}return a};
J4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.o[b][c].reset();this.A=a;this.g=0;this.l=this.Kc=1};
var iza=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],jza=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],kza=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],lza=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];P4.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.l=this.C;this.o=this.D;this.g=this.l;var c=(a<<2)+(b<<1);this.C.reset(c);this.D.reset(c);this.F.reset((a<<2)+(b<<1)+1)};
E4.prototype.reset=function(a){this.B=a;this.g.clear();this.A=this.o;this.o.reset(a,0);this.C.reset(a,1)};R4.prototype.reset=function(){};g.p(S4,R4);S4.prototype.o=function(a){var b=[];this.g||(this.g=B4(this.l),b.push(this.g));a=g.ma(a.firstChild.childNodes);for(var c=a.next();!c.done;c=a.next())rza(c.value,this.g.id,b);return b};g.p(U4,R4);
U4.prototype.o=function(a){var b=[];this.g||(this.g=B4(),this.l[this.g.id]=this.g,b.push(this.g));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.l[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=B4());
var k={};f&&(g.Ga(k,f.params),f=f.params.ib)&&(k.ib={},g.Ga(k.ib,f));e.getAttribute("rc")&&(k.hp=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.YH=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Ug=0>f||8<f?7:f);e.getAttribute("ah")&&(k.xi=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.Ri=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.lk=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.lk=0));e.getAttribute("bc")&&(k.ib||(k.ib={}),k.ib.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.ib||(k.ib={}),k.ib.Ye=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.ib||(k.ib={}),k.ib.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.LU=(0,window.parseInt)(e.getAttribute("sd"),10));f=(0,window.parseInt)(e.getAttribute("d"),
10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"0";c=new z4(c,f,0,e,k)}else c=null}this.l[d]=c;b.push(c);break;case "text":for(d=[],rza(a,this.g.id,d),d=g.ma(d),c=d.next();!c.done;c=d.next())c=c.value,this.l[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.p(V4,R4);V4.prototype.reset=function(){this.H={};this.g=null;this.D=[];this.l=null;this.F=!0};
V4.prototype.o=function(a,b){a.firstChild.getAttribute("format");b=b||0;Number.isFinite(b);for(var c,d,e=g.ma(a.firstChild.childNodes),f=e.next();!f.done;f=e.next())if(f=f.value,1==f.nodeType)switch(f.tagName){case "head":c=f;break;case "body":d=f}if(c)for(c=g.ma(c.childNodes),e=c.next();!e.done;e=c.next())if(e=e.value,1==e.nodeType)switch(e.tagName){case "pen":f=e.getAttribute("id");var k=this.A,l={},m=e.getAttribute("p");m&&g.Ga(l,this.A[m]);m=X4(e,"b");null!=m&&(l.bold=m);m=X4(e,"i");null!=m&&
(l.ts=m);m=X4(e,"u");null!=m&&(l.underline=m);m=Y4(e,"et");null!=m&&(l.Xh=m);m=Y4(e,"of");null!=m&&(l.offset=m);m=Z4(e,"bc");null!=m&&(l.background=m);m=Z4(e,"ec");null!=m&&(l.Pw=m);m=Z4(e,"fc");null!=m&&(l.color=m);m=Y4(e,"fs");void 0!=m&&0!=m&&(l.fontFamily=m);m=W4(e,"sz");void 0!=m&&(l.oj=m/100-1);m=W4(e,"bo");void 0!=m&&(l.Ye=m/255);e=W4(e,"fo");void 0!=e&&(l.Hh=e/255);k[f]=l;break;case "ws":f=e.getAttribute("id");this.K[f]=sza(this,e);break;case "wp":f=e.getAttribute("id"),this.I[f]=tza(this,
e)}if(d){c=b;e=[];f=[];d=g.ma(d.childNodes);for(k=d.next();!k.done;k=d.next())if(k=k.value,1==k.nodeType)switch(k.tagName){case "w":this.g=uza(this,k,c,!1);(k=this.H[this.g.id])&&k.end>this.g.start&&(k.end=this.g.start);this.H[this.g.id]=this.g;e.push(this.g);break;case "p":if(l=wza(this,k,c),0<l.length)for(l[0].windowId==this.B&&(this.g=uza(this,k,c,!0),e.push(this.g)),k=g.ma(l),l=k.next();!l.done;l=k.next())l=l.value,l.windowId=this.g.id,this.g.l.push(l),f.push(l),e.push(l)}this.D=f;d=e}else d=
[];return d};g.p($4,cza);$4.prototype.A=function(a,b,c,d,e){if(c<d){var f="_"+A4++;c=c/1E3-this.D;d=d/1E3-this.D;a=new z4(c,d-c,5,f,{textAlign:0,Ug:0,xi:2.5*b,Ri:5.33*a});e=new y4(c,d-c,5,f,e);this.o.push(a);this.o.push(e)}};
g.p(b5,R4);b5.prototype.o=function(a){a=new $4(a,a.byteLength,this.l);if(yza(a)){for(;a.g<a.l.byteLength;)for(0==a.version&&(a.C=xza(a)*(1E3/45)),a.B=a5(a);0<a.B;a.B--){var b=a5(a),c=a5(a),d=a5(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.C,type:this.track,Kw:c,Lw:d,order:b.g.length}))}hza(this.g,a);return a.o}return[]};
b5.prototype.reset=function(){this.g.clear()};g.p(e5,R4);
e5.prototype.o=function(a,b){for(var c=[],d=a.split(Wza),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Xza.test(f)){var l=v5.exec(f);if(l&&3<=l.length){var m=f5(l[1]);l=f5(l[2])-m;m+=k;f=f.substring(v5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");v5.lastIndex=0;var n=f;f={};this.g||(this.g=B4({Hs:0}),c.push(this.g));var q=this.g;k=5;if(0>n.indexOf("<")&&0>n.indexOf("&"))c.push(new y4(m,l,k,q.id,n,!1,g.Yb(f)?void 0:f));else{n=n.split(Yza);1!=n.length&&(k=6,q="_"+Zza++,q=new z4(m,l,k,q,{}),c.push(q));
for(var r=m,u=0;u<n.length;u++){var D=n[u];if(0==u%2){var I=g.Ur("<html>"+D+"</html>");if(I.getElementsByTagName("parsererror").length){var T=I.createElement("span");T.appendChild(I.createTextNode(D))}else T=I.firstChild;Bza(this,r,l-(r-m),k,q,0<u,T,f,c)}else r=f5(D)}}}v5.lastIndex=0}}return c};
var Zza=0,Xza=/^NOTE/,Wza=/(?:\r\n|\r|\n){2,}/,v5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3}).*(?:\r\n|\r|\n)","gm"),Yza=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.p(g5,g.L);g5.prototype.trackCount=function(){return c5(this.l,!0).length};
g5.prototype.Nd=function(){this.g=null};
g5.prototype.V=function(){g.L.prototype.V.call(this);this.Nd()};
g5.prototype.yC=function(){return!1};g.p(h5,g5);g.h=h5.prototype;g.h.Bs=function(a,b){var c=this.Wk(a),d=(0,g.z)(function(c){this.o=null;b(c.responseText,a)},this);
this.Nd();this.o=g.oE(c,{format:"RAW",Jb:d,withCredentials:!0})};
g.h.Cs=function(a,b,c,d){this.A=c;if(d)for(b=g.ma(d.captionTracks),c=b.next();!c.done;c=b.next())d5(this.l,c.value);a()};
g.h.Wk=function(a){var b=a.Qa(),c={};if(this.A||a.o)c.fmt=this.A||"srv"+a.o;a.g&&(c.tlang=a.g.languageCode);return g.dE(b,c)};
g.h.Nd=function(){g5.prototype.Nd.call(this);this.o&&this.o.abort()};
g.h.V=function(){this.Nd();g5.prototype.V.call(this)};i5.prototype.contains=function(a){a=g.fb(this.ob,a);return 0<=a||0>a&&1==(-a-1)%2};
i5.prototype.length=function(){return this.ob.length/2};g.p(j5,g.L);g.h=j5.prototype;g.h.V=function(){g.L.prototype.V.call(this);this.l&&this.l.cancel()};
g.h.AA=function(a){var b=this;if(this.F.xc())var c=this.B.O(this.A,"progresssync",function(){b.F.index.Pb()&&(b.reset(),b.g=null,Fza(b,b.A.getCurrentTime()),b.B.Ba(c))});
else Fza(this,a)};
g.h.reset=function(){this.C=new i5;this.l&&(this.l.cancel(),this.l=null)};
g.h.vz=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.Ai(a);!a||this.l||this.g&&30<this.g.startTime-this.A.getCurrentTime()||(a=this.g,a=a.g.ul(a),!g.Y(this.A).experiments.g("disable_captions_unknown_requests")&&!a.Ga[0].duration)||(this.C.contains(a.Ga[0].xa)||Gza(this,a),this.g=g.Ja(a.Ga));this.I.start()};
g.h.jS=function(a){var b=!(this.D?a.response:a.responseText)||400<=a.status;if(!g.Y(this.A).experiments.g("disable_captions_redirects_redux")){var c=g.EK(a);if(c){a=g.kK(this.o,this.K,{});b=this.o;g.gK(b.g,a,c);b.requestId=a.get("req_id");Gza(this,this.o);return}}b||null===this.H||(this.D?this.H(a.response,1E3*this.o.Ga[0].startTime):this.H(a.responseText,1E3*this.o.Ga[0].startTime));this.l=this.o=null};g.p(k5,g5);g.h=k5.prototype;g.h.Bs=function(a,b){this.Nd();var c=Hza(this,a.l);if(c){var d=c.index.Mn(c.index.Hf());g.Y(this.A).experiments.g("html5_disable_caption_starttime")||(d-=c.index.Md(c.index.Hf()));d*=1E3;var e=g.Y(this.A).Ma;this.B=new j5(new g.QJ,this.A,c,function(c,e){b(c,a,e,d)},e||g.dH(c.info),(0,g.z)(function(){e&&(this.B&&this.B.reset(),this.g&&this.g.reset(),this.C=!0)},this))}};
g.h.yC=function(){var a=this.C;this.C=!1;return a};
g.h.Cs=function(a){if(g.Y(this.A).Ma)d5(this.l,new g.iI({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),d5(this.l,new g.iI({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));else for(var b in this.o.g){var c=this.o.g[b];if(g.gH(c.info.mimeType)&&"rawcc"!=b&&("386"!=b||!g.Y(this.A).experiments.g("html5_manifestless_captions_fmt3_killswitch"))){var d="en",e="English",f=".en";if(c=
c.info.captionTrack)d=c.languageCode,e=c.displayName,f=c.vssId;d5(this.l,new g.iI({format:1,languageCode:d,languageName:e,name:"",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:f}))}}a()};
g.h.Nd=function(){g5.prototype.Nd.call(this);this.B&&(this.B.dispose(),this.B=null)};
g.h.Wk=function(){return""};
g.h.V=function(){this.Nd();g5.prototype.V.call(this)};g.p(l5,C4);l5.prototype.kq=function(a){var b=this.D.l;C4.prototype.kq.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.l==e)var d=f;else{d={};g.Ga(d,c.l);g.Ga(d,$za);var e=c.l;var f=d}bza(this,c,d)}};
var $za={Br:!0};g.p(m5,C4);g.h=m5.prototype;g.h.QC=function(){g.Zt(this.X)};
g.h.nS=function(){g.sq(this.element,"ytp-rollup-mode");this.Ni(this.ia,!0)};
g.h.Yx=function(){return this.H};
g.h.Xx=function(){return this.D.params.hp*n5(this)};
g.h.Ni=function(a,b){this.ia=a;if(n5(this)){for(var c=0,d=0;d<this.o.length&&c<a.length;d++)this.o[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.o.concat(a.slice(c)));c=this.H;this.H=0;C4.prototype.Ni.call(this,a);this.H=Math.max(c,this.A.offsetWidth+1);c=this.D.params.hp*n5(this)-this.A.offsetHeight;c!=this.N&&(b||(0,window.isNaN)(this.N)||(g.S(this.element,"ytp-rollup-mode"),g.Yt(this.X)),g.qh(this.A,"transform",c?"translateY("+c+"px)":""),this.N=c);C4.prototype.Ni.call(this,a)}else C4.prototype.Ni.call(this,
a)};g.p(o5,g5);g.h=o5.prototype;g.h.Bs=function(a,b){var c=this.Wk(a),d=(0,g.z)(function(c){this.o=null;b(c.responseText,a)},this);
this.Nd();this.o=g.oE(c,{format:"RAW",Jb:d,withCredentials:!0})};
g.h.Cs=function(a,b,c){var d=this.B;b={type:"list",tlangs:1,v:this.A,fmts:Number(b||!1),vssids:1};this.bz&&(b.asrs=1);d=g.dE(d,b);b=(0,g.z)(function(b){this.o=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.l,e=g.ma(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("formats");var n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),r=m.getAttribute("name"),u=m.getAttribute("kind"),D=m.getAttribute("id"),I="true"==m.getAttribute("lang_default"),
T="true"==m.getAttribute("cantran");m=m.getAttribute("vss_id");d5(d,new g.iI({formats:l,format:c,languageCode:n,languageName:q,name:r,kind:u,id:D,is_servable:!0,is_translateable:T,vss_id:m,is_default:I}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),q=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),u="true"==b[e].getAttribute("lang_default"),l={languageCode:l,languageName:n,languageOriginal:q,id:r,
is_default:u},this.C[l.languageCode]=l.languageName,this.D.push(new g.hI(l))}a()},this);
this.Nd();this.o=g.oE(d,{format:"RAW",Jb:b,withCredentials:!0})};
g.h.Wk=function(a){var b=this.B,c={v:this.A,type:"track",lang:a.l,name:a.B,kind:a.A,fmt:a.o};a.g&&(c.tlang=w4(a));return b=g.dE(b,c)};
g.h.Nd=function(){g5.prototype.Nd.call(this);this.o&&this.o.abort()};
g.h.V=function(){this.Nd();g5.prototype.V.call(this)};g.p(r5,g.sV);g.h=r5.prototype;g.h.V=function(){if(this.F){var a=this.K.app.B;a&&Wya(a)}else Oza(this,!1);g.sV.prototype.V.call(this)};
g.h.Wz=function(){return this.F?!this.l.za:this.ia||this.l.captionTracks.length&&this.g.getAudioTrack().Pk?!0:Jza(this)};
g.h.load=function(a){g.sV.prototype.load.call(this);this.D=this.g.getAudioTrack();if(this.B||a)this.o?(this.F&&!this.A.experiments.g("disable_native_caption_api")?Lza(this,!0):a?this.iC(a,this.o):3!=this.g.Sa()&&this.B.Bs(this.o,(0,g.z)(this.iC,this)),this.g.ua("captionschanged",v4(this.o))):this.g.ua("onCaptionsTrackListChanged");else{var b;Iza(this.l,this.K)?b=new k5(this.l.pa,this.g):this.l.captionTracks.length?b=new h5(this.l):b=new o5(this.l.Zm,this.l.videoId,this.l.Xg||this.A.Xg||g.jO(this.l,
"yt:cc_default_lang")||this.A.Ca,this.l.Ym);this.B=b;b.Cs((0,g.z)(this.QS,this),!0,this.F?"vtt":void 0,this.g.getAudioTrack())}};
g.h.unload=function(){this.F?this.A.experiments.g("disable_native_caption_api")?Wya(this.K.app.B):this.o&&Lza(this,!1):(this.fa&&g.$t(this.fa),g.kV(this.g,"captions"),this.M=[],this.B&&this.B.Nd(),this.I&&g.hV(this.g,this.I),this.Nu());g.sV.prototype.unload.call(this);var a=g.UU(this.g.app);a&&a.C&&g.oP(a.C.o);this.g.ua("captionschanged",{})};
g.h.QS=function(){if(this.N||Jza(this))var a=Kza(this,this.N);if(this.F||this.ia){for(var b=c5(this.B.l,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.jI(e),srclang:w4(e),id:e.toString()};this.ia||(f.src=this.B.Wk(e));e==a&&(f["default"]=1);c.push(g.K("TRACK",f))}a=this.K.app.B;for(b=0;b<c.length;b++)a.g.appendChild(c[b]);(c=this.K.app.B.g)&&c.textTracks&&c.textTracks.addEventListener&&!this.A.experiments.g("disable_native_caption_api")&&this.W.O(c.textTracks,"change",this.RS)}else!this.o&&
a&&s5(this,a),this.g.ua("onCaptionsTrackListChanged"),this.g.ua("onApiChange")};
g.h.RS=function(){for(var a=this.K.app.B.g.textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=c5(this.B.l,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.o:null)!=b&&s5(this,b,!0)};
g.h.VU=function(){this.A.experiments.g("disable_native_caption_api")?this.loaded&&!this.F&&this.unload():!this.o&&this.F||this.unload()};
g.h.iC=function(a,b,c,d){if(a){this.B.yC()&&(this.M=[],g.kV(this.K,"captions"),this.da.Yk());a=Eza(this.B,a,b,c,d);g.hV(this.g,a);if(this.N&&(a={trackName:b.B,trackKind:b.A,trackLangCode:w4(b)},b.g&&(a.fromLangCode=b.l),g.bV(this.g,"cc",a),!this.ia&&this.o!=(this.D&&this.D.Pk))){!this.N||g.sM(this.A)||g.zM(this.A)||(g.$t(this.fa),b=B4({Ug:0,xi:5,Ri:5,hp:2,textAlign:0,lk:0,lang:"en"}),this.X=[b],a=g.V("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON"),this.ma||(c=new g.NH(g.Foa()),g.M(this,c),this.ma=c.element),
c=b.end-b.start,(d=g.jI(this.o))&&this.X.push(new y4(b.start,c,0,b.id,d)),this.X.push(new y4(b.start,c,0,b.id,a[0]),new y4(b.start,c,0,b.id,this.ma,!0),new y4(b.start,c,0,b.id,a[1],!0)),g.hV(this.g,this.X),g.Yt(this.fa));if(this.N||g.sM(this.A))u5(this,"module-enabled",!0),this.D&&(this.D.g=this.o);(b=g.UU(this.g.app))&&b.C&&g.oP(b.C.o)}this.N=!1}};
g.h.KL=function(a){this.M.push(a);this.da.Yk()};
g.h.LL=function(a){g.Ua(this.M,a);var b=Iza(this.l,this.K)&&this.A.Ma;!this.A.experiments.g("disable_remove_displayed_close_caption_cue")&&b&&g.jV(this.g,[a]);this.da.Yk()};
g.h.OT=function(a){if(a instanceof z4){var b=this.P[a.id];b&&b.D!=a&&(b.dispose(),delete this.P[a.id],b=null);b||(b=Mza(this,a))&&(this.P[a.id]=b)}else b=a.windowId,this.Y[b]||(this.Y[b]=[]),this.Y[b].push(a)};
g.h.aU=function(){Nza(this,this.X);this.X=null};
g.h.ZD=function(){this.da.stop();g.Zb(this.Y);this.M.sort(g.oQ);var a=this.M;if(this.I){var b=(0,g.Jd)(a,function(a){return-1==this.I.indexOf(a)},this);
b.length&&(a=b)}(0,g.B)(a,this.OT,this);g.Kb(this.P,function(a,b){this.Y[b]?(a.element.parentNode||g.mV(this.g,a.element,4),a.Ni(this.Y[b])):(a.dispose(),delete this.P[b])},this)};
g.h.PC=function(){p5(this,{},!0)};
g.h.ar=function(){var a=t5.ib;a={background:a.background,backgroundOpacity:a.Ye,charEdgeStyle:a.Xh,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.oj,textOpacity:a.Hh,windowColor:t5.windowColor,windowOpacity:t5.xk};var b=q5(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.Qu=function(a,b){var c={};g.Ga(c,q5(this,"display-settings"));g.Ga(c,a);p5(this,c,b);this.g.R("captionssettingschanged")};
g.h.Nu=function(){!this.F&&this.loaded&&(g.Kb(this.P,function(a,b){a.dispose();delete this.P[b]},this),this.ZD())};
g.h.Ps=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.ad(b,-2,4);this.Qu({fontSizeIncrement:c});return c;case "reload":b&&!this.F&&s5(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.A.xb&&u5(this,"module-enabled",!!b);break;case "track":if(!this.B)return{};if(b){if(this.F)break;if(!g.Ca(b))break;if(g.Yb(b)){s5(this,null,!0);break}for(var d=c5(this.B.l,!0),e=0;e<d.length;e++){var f=d[e];f.l!=b.languageCode||c&&f.C!=b.languageName||(c=b.translationLanguage?Vya(f,
b.translationLanguage):f)}!c||c==this.o&&this.loaded||s5(this,c,!0)}else return this.loaded&&this.o&&this.o!=(this.D&&this.D.Pk)?v4(this.o):{};return"";case "tracklist":return this.B?(0,g.H)(c5(this.B.l,!(!b||!b.includeAsr)),function(a){return v4(a)}):[];
case "translationLanguages":return this.B?this.B.D:[];case "displaySettings":c=this.ar();if(g.sM(this.A)&&b&&g.Ca(b))if(b.reset)this.PC();else{f={};for(d in b)switch(d){case "color":case "background":case "windowColor":f[d]=Pza(b[d],c[d]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[d]=Qza(b[d],c[d]);break;case "charEdgeStyle":f[d]=Sza(b[d],c[d]);break;case "fontSizeIncrement":f[d]=Vza(b[d],c[d]);break;case "fontFamilyOption":f.fontFamily=Uza(b[d],c[d])}for(e in f)f[e+
"Override"]=!0;this.Qu(f,!0);c=this.ar()}c.fontFamilyOption=Tza[c.fontFamily];c.charEdgeStyle=Rza[c.charEdgeStyle];return c;case "sampleSubtitles":this.F||void 0==b||Oza(this,!!b);break;case "xmlTrack":b&&this.A.xb&&(this.F||s5(this,new g.iI({languageName:b.name}),!1,b.xml))}};
g.h.IL=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.A.xb&&a.push("stickyLoading","xmlTrack");return a};
g.h.JL=function(){var a=this.o;return a?{cc:a.D}:{}};
g.h.JD=function(){this.loaded&&this.o?(u5(this,"module-enabled",!1),this.unload()):s5(this,this.o||Kza(this,!0),!0)};
g.h.lP=function(){this.l.captionTracks.length&&(this.loaded&&this.unload(),this.Wz()&&this.load())};g.gY.captions=r5;})(_yt_player);
