(function(g){var window=this;var aAa=function(a,b,c,d){var e=b.oc();g.U(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.rd(c,d?d:"mqdefault.jpg");var k=b instanceof g.VN?g.GV(b.lengthSeconds):null,l=!!f;f=l&&"RD"==(new g.pQ(f.substr(0,2),f.substr(2))).type;var m=b instanceof g.VN?b.za:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,aria_label:b.Om||g.V("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Qn(c),is_live:m,
is_list:l,is_mix:f,background:d?"background-image: url("+d+")":""};b instanceof g.rQ&&(c.playlist_length=b.getLength());a.update(c)},w5=function(a,b){g.TH.call(this,{G:"div",
aa:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.l=a;this.created=!1},x5=function(a){var b={G:"span",
L:"ytp-upnext-top",J:[{G:"span",L:"ytp-upnext-header",J:[g.V("YTP_PLAYLIST_UP_NEXT")]},{G:"span",L:"ytp-upnext-title",J:["{{title}}"]},{G:"span",L:"ytp-upnext-author",J:["{{author}}"]}]},c={role:"button",href:"{{url}}","aria-label":g.V("YTP_AUTOPLAY_NEXT")};b={G:"div",L:"ytp-upnext",U:{"aria-label":"{{aria_label}}"},J:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",U:{style:"{{background}}"}},b,{G:"a",L:"ytp-upnext-autoplay-icon",U:c,J:[{G:"svg",U:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
J:[{G:"circle",L:"ytp-svg-autoplay-circle",U:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",U:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",U:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",J:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",
J:[g.V("YTP_AUTOPLAY_PAUSED_3")]}]}]};g.W.call(this,b);this.A=null;b=this.sa["ytp-upnext-cancel"];this.A=new g.W({G:"button",aa:["ytp-upnext-cancel-button","ytp-button"],U:{tabindex:"0","aria-label":g.V("YTP_AUTOPLAY_CANCEL")},J:[g.V("YTP_CANCEL")]});g.M(this,this.A);this.A.T("click",this.tP,this);this.A.va(b);this.l=a;this.I=this.sa["ytp-svg-autoplay-ring"];this.D=this.C=this.o=this.B=null;this.F=new g.Xt(this.gn,5E3,this);g.M(this,this.F);this.H=0;this.O(this.sa["ytp-upnext-autoplay-icon"],"click",
this.ER);this.wB();this.O(a,"autonavvisibility",this.wB);this.O(a,"mdxnowautoplaying",this.SQ);this.O(a,"mdxautoplaycanceled",this.TQ);this.O(a,"mdxautoplayupnext",this.dE);3==this.l.Sa()&&(a=(a=g.TU(g.OU(this.l)))?a.CI():null)&&this.dE(a)},bAa=function(a,b){a.B=b;
aAa(a,b,g.Y(a.l),"hqdefault.jpg")},y5=function(a,b){if(!a.o){g.VF("a11y-announce",g.V("YTP_PLAYLIST_UP_NEXT")+" "+a.B.title);
a.H=g.fG();a.o=new g.Xt((0,g.z)(a.iq,a,b),25);a.iq(b);var c=b||g.Y(a.l).experiments.l("autoplay_time")||1E4;a.l.ua("onAutonavCoundownStarted",c)}g.sq(a.element,"ytp-upnext-autoplay-paused")},A5=function(a){z5(a);
a.H=g.fG();a.iq();g.S(a.element,"ytp-upnext-autoplay-paused")},z5=function(a){a.o&&(a.o.dispose(),a.o=null)},B5=function(a,b){b=void 0===b?!1:b;
var c=g.Y(a.l);if(c.experiments.g("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var d=window.Notification.permission;g.bV(a.l,"xwebnotifications",{permission:d});"default"==d?window.Notification.requestPermission():"granted"!=d||window.document.hasFocus()||(d=a.B.oc(),a.gn(),a.C=new window.Notification(g.V("YTP_PLAYLIST_UP_NEXT"),{body:d.title,icon:d.rd(c)}),a.D=a.O(a.C,"click",a.tR),a.F.start())}z5(a);a.l.Rj(!1,b)},cAa=function(a){w5.call(this,a,"subscribecard-endscreen");
var b=a.ea();this.o=new g.W({G:"div",L:"ytp-subscribe-card",J:[{G:"img",L:"ytp-author-image",U:{src:b.profilePicture}},{G:"div",L:"ytp-subscribe-card-right",J:[{G:"div",L:"ytp-author-name",J:[b.author]},{G:"div",L:"html5-subscribe-button-container"}]}]});g.M(this,this.o);this.o.va(this.element);this.A=new g.l_(g.V("YTP_SUBSCRIBE"),null,g.V("YTP_UNSUBSCRIBE"),null,!0,!1,b.Zl,b.subscribed,"trailer-endscreen",null,null,a);g.M(this,this.A);this.A.va(this.o.sa["html5-subscribe-button-container"]);this.hide()},
C5=function(a){var b=g.Y(a),c=g.OJ||g.ef?{style:"will-change: opacity"}:void 0,d=b.l&&!b.B,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.W.call(this,{G:"a",aa:e,U:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{G:"div",L:"ytp-videowall-still-image",U:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",J:[{G:"span",L:"ytp-videowall-still-info-bg",J:[{G:"span",L:"ytp-videowall-still-info-content",U:c,J:[{G:"span",L:"ytp-videowall-still-info-title",J:["{{title}}"]},{G:"span",
L:"ytp-videowall-still-info-author",J:["{{author_and_views}}"]},{G:"span",L:"ytp-videowall-still-info-live",J:[g.V("YTP_LIVE")]},{G:"span",L:"ytp-videowall-still-info-duration",J:["{{duration}}"]}]}]}]},{G:"span",aa:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},g.V("YTP_PLAYLIST"),{G:"span",L:"ytp-videowall-still-listlabel-length",J:[" (",{G:"span",J:["{{playlist_length}}"]},")"]}]},{G:"span",aa:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],J:[{G:"span",L:"ytp-videowall-still-listlabel-mix-icon"},g.V("YTP_MIX"),{G:"span",L:"ytp-videowall-still-listlabel-length",J:[" (50+)"]}]}]});this.A=d;this.o=a;this.l=null;this.T("click",this.B);this.T("keypress",this.C);g.Y(a).N&&(a=a.app.da,b=this.element,g.C(a.g,b),g.Sa(a.g,b),c=String(a.F++),b.setAttribute("data-visual-id",c),g.$e(this,(0,g.z)(a.D,a,b)))},D5=function(a){w5.call(this,a,"videowall-endscreen");
this.M=a;this.F=0;this.A=[];this.H=this.D=this.C=null;this.I=this.P=!1;this.B=new g.DF(this);g.M(this,this.B);this.K=new g.Xt(g.Fa(g.S,this.element,"ytp-show-tiles"),0);g.M(this,this.K);var b=new g.W({G:"button",aa:["ytp-button","ytp-endscreen-previous"],U:{"aria-label":g.V("YTP_PREVIOUS")},J:[g.soa()]});g.M(this,b);b.va(this.element);b.T("click",this.uN,this);this.N=new g.NH({G:"div",L:"ytp-endscreen-content"});g.M(this,this.N);this.N.va(this.element);b=new g.W({G:"button",aa:["ytp-button","ytp-endscreen-next"],
U:{"aria-label":g.V("YTP_NEXT")},J:[g.toa()]});g.M(this,b);b.va(this.element);b.T("click",this.tN,this);this.o=new x5(a);g.M(this,this.o);g.mV(this.l,this.o.element,4);g.Y(a).experiments.g("new_autonav_styling")&&g.S(this.o.element,"ytp-new-autonav");this.hide()},E5=function(a){return g.nV(a.l)&&a.mq()&&!a.H},dAa=function(a,b){return(0,g.H)(b.suggestions,function(b){b=g.aZ(b);
g.M(a,b);return b})},F5=function(a){var b=a.qt();
b!=a.P&&(a.P=b,a.l.R("autonavvisibility"))},G5=function(a){g.sV.call(this,a);
g.RG({YTP_AUTOPLAY_CANCEL:"Cancel autoplay",YTP_AUTOPLAY_NEXT:"Play next video",YTP_AUTOPLAY_PAUSED_3:"Autoplay is paused",YTP_CANCEL:"Cancel",YTP_MIX:"Mix",YTP_PLAYLIST_UP_NEXT:"Up Next",YTP_UNSUBSCRIBE:"Unsubscribe"});this.l=null;this.o=new g.DF(this);g.M(this,this.o);this.A=g.Y(a);eAa(a)?this.l=new D5(this.g):this.A.ba?this.l=new cAa(this.g):this.l=new w5(this.g);g.M(this,this.l);g.mV(this.g,this.l.element,4);this.NC();this.o.O(a,"videodatachange",this.NC,this);this.o.O(a,"crn_endscreen",this.zL,
this);this.o.O(a,"crx_endscreen",this.AL,this)},eAa=function(a){a=g.Y(a);
return a.Xc&&!a.ba};
g.p(w5,g.TH);w5.prototype.create=function(){this.created=!0};
w5.prototype.destroy=function(){this.created=!1};
w5.prototype.mq=function(){return!1};
w5.prototype.qt=function(){return!1};g.p(x5,g.W);g.h=x5.prototype;g.h.gn=function(){this.C&&(this.F.stop(),this.Ba(this.D),this.D=null,this.C.close(),this.C=null)};
g.h.wB=function(){g.SH(this,g.PU(this.l))};
g.h.tR=function(){window.focus();this.gn()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.iq=function(a){a=a||g.Y(this.l).experiments.l("autoplay_time")||1E4;var b=Math.min(g.fG()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.Sa()?B5(this,!0):this.o&&this.o.start()};
g.h.ER=function(a){!g.Pd(this.A.element,g.sF(a))&&g.mX(a,this.l)&&B5(this)};
g.h.tP=function(){g.RU(this.l,!0)};
g.h.SQ=function(a){this.l.Sa();this.show();y5(this,a)};
g.h.dE=function(a){this.l.Sa();this.B&&this.B.oc().videoId==a.oc().videoId||bAa(this,a)};
g.h.TQ=function(){this.l.Sa();z5(this);this.hide()};
g.h.V=function(){z5(this);this.gn();g.W.prototype.V.call(this)};g.p(cAa,w5);g.p(C5,g.W);C5.prototype.fk=function(){g.qV(this.o,this.element);var a=this.l.oc().videoId,b=this.l.getPlaylistId();g.m0(this.o.app,a,this.l.ee,b,void 0,void 0,void 0)};
C5.prototype.B=function(a){g.mX(a,this.o,this.A,this.l.ee||void 0)&&this.fk()};
C5.prototype.C=function(a){switch(a.keyCode){case 13:case 32:g.xF(a)||(this.fk(),g.wF(a))}};g.p(D5,w5);g.h=D5.prototype;g.h.create=function(){w5.prototype.create.call(this);var a=this.l.ea();a&&(this.C=dAa(this,a),this.D=a);this.Eg();this.B.O(this.l,"appresize",this.Eg);this.B.O(this.l,"onVideoAreaChange",this.Eg);this.B.O(this.l,"videodatachange",this.vN);this.B.O(this.l,"autonavchange",this.vA);this.B.O(this.l,"autonavcancel",this.sN);this.B.O(this.element,"transitionend",this.SS)};
g.h.destroy=function(){g.FF(this.B);g.bf(this.A);this.A=[];this.C=null;w5.prototype.destroy.call(this);g.sq(this.element,"ytp-show-tiles");this.K.stop()};
g.h.mq=function(){return 1!=this.D.autonavState};
g.h.show=function(){w5.prototype.show.call(this);g.sq(this.element,"ytp-show-tiles");g.Y(this.l).g?g.Zt(this.K):this.K.start();(this.I||this.H&&this.H!=this.D.clientPlaybackNonce)&&g.RU(this.l,!1);var a=E5(this);g.nV(this.l)&&g.Y(this.l).experiments.g("ui_logging")&&g.bV(this.l,"end",{cancelButtonShow:a?"1":"0",state:this.mq()?"enabled":"disabled"});a?(F5(this),2==this.D.autonavState?g.Y(this.l).experiments.g("fast_autonav_in_background")&&3==this.l.Di()?B5(this.o,!0):y5(this.o):3==this.D.autonavState&&
A5(this.o)):(g.RU(this.l,!0),F5(this))};
g.h.hide=function(){w5.prototype.hide.call(this);A5(this.o);F5(this)};
g.h.SS=function(a){g.sF(a)==this.element&&this.Eg()};
g.h.Eg=function(){if(this.C&&this.C.length){g.S(this.element,"ytp-endscreen-paginate");var a=g.eV(this.M,!0),b=g.gI(this.M);b&&(b=b.td()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,r=e/2,u=b<=f-2&&n>=r*m,D=e<=k-2&&n>=q*m;if((q+1)/r*d/c>c/(q/(r+1)*d)&&D)n-=q*m,e+=2;else if(u)n-=r*m,b+=2;else if(D)n-=q*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.ad(a.width/m||1,1,1.21);n*=g.ad(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.N.element;g.Ih(a,m,n);g.qh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});bAa(this.o,this.C[0]);g.U(this.element,"ytp-endscreen-takeover",E5(this));F5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,r=0,d&&f>=b-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&
2>f?0==k&&0==f&&(r=2):r=2),q=g.bd(q+this.F,l),0!=r){u=this.A[c];u||(u=new C5(this.l),this.A[c]=u,a.appendChild(u.element));D=Math.floor(n*k/e);var I=Math.floor(m*f/b),T=Math.floor(n*(k+r)/e)-D-4,na=Math.floor(m*(f+r)/b)-I-4;g.xh(u.element,I,D);g.Ih(u.element,na,T);g.qh(u.element,"transitionDelay",(k+f)/20+"s");g.U(u.element,"ytp-videowall-still-mini",1==r);g.U(u.element,"ytp-videowall-still-large",2<r);r=u;q=this.C[q];r.l!=q&&(r.l=q,aAa(r,q,g.Y(r.o),g.qq(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":
"mqdefault.jpg"),u=(q=q.ee)&&q.itct)&&(q=r.o,g.Y(q).N&&(q=q.app.da,r=r.element,D=r.getAttribute("data-visual-id"),g.C(q.g,r),g.oV(q,"onLogServerVeCreated",{id:D,tracking_params:u})));c++}g.U(this.element,"ytp-endscreen-paginate",c<l);for(b=this.A.length-1;b>=c;b--)e=this.A[b],g.Id(e.element),g.af(e);this.A.length=c}};
g.h.vN=function(){var a=this.l.ea();this.D!=a&&(this.F=0,this.C=dAa(this,a),this.D=a,this.Eg())};
g.h.tN=function(){this.F+=this.A.length;this.Eg()};
g.h.uN=function(){this.F-=this.A.length;this.Eg()};
g.h.GK=function(){return!!this.o.o};
g.h.vA=function(a){1==a?(this.I=!1,this.H=this.D.clientPlaybackNonce,z5(this.o),this.g&&this.Eg()):(this.I=!0,this.g&&E5(this)&&(2==a?y5(this.o):3==a&&A5(this.o)))};
g.h.sN=function(a){if(a){for(a=0;a<this.A.length;a++)g.rV(this.M,this.A[a].element,!0);this.vA(1)}else this.H=null,this.I=!1;this.Eg()};
g.h.qt=function(){return this.g&&E5(this)};g.p(G5,g.sV);g.h=G5.prototype;g.h.Vz=function(){var a=this.g.ea(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!eAa(this.g)||b;a=g.nO(a,"ypc_module");var c=g.n0(this.g.app);return b&&!a&&!c};
g.h.Uz=function(){return this.l.qt()};
g.h.CK=function(){return this.Uz()?this.l.GK():!1};
g.h.V=function(){g.kV(this.g,"endscreen");g.sV.prototype.V.call(this)};
g.h.load=function(){g.sV.prototype.load.call(this);this.l.show();g.Y(this.g).ba&&.01>Math.random()&&g.bV(this.g,"end",{trailerEndscreenShow:1})};
g.h.unload=function(){g.sV.prototype.unload.call(this);this.l.hide();this.l.destroy()};
g.h.zL=function(a){this.Vz()&&(this.l.created||this.l.create(),"load"==a.ka&&this.load())};
g.h.AL=function(a){"load"==a.ka&&this.loaded&&this.unload()};
g.h.NC=function(){g.kV(this.g,"endscreen");var a=Math.max(1E3*(this.g.ea().lengthSeconds-10),0);a=new g.mQ(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.M(this,a);var b=new g.mQ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.M(this,b);g.hV(this.g,[a,b])};g.gY.endscreen=G5;})(_yt_player);
